### PR TITLE
Updating xtend dependency to latest version

### LINKED ISSUE #2: Update `xtend` version
This library relies on version 0.2.6 of `xtend` which itself relies on a deprecated version of `object-keys`.  This dependency should be updated (or removed if not needed).

### PR DESCRIPTION
**Pull request by ajcrites**
Fixes #2

### CODE REVIEW

**Comment by ajcrites** [comment]
Fixes #2

**Comment by fgnass** [comment]
Any chance this could get merged?

**Comment by jonathanong** [comment]
:+1: @thlorenz

**Comment by thlorenz** [comment]
Sorry couldn't merge (and huge sorry for not responding til now).
Could you please rebase? I'll merge then. THanks.

**Comment by ajcrites** [comment]
What needs to be rebased? This seems to be up-to-date with the target branch.

**Comment by thlorenz** [comment]
Your're right (I tried the git _rebase and merge_ button which told me there are conflicts).
It applied fine and I published as v0.3.0

**Pull request closed without merging**
